server:
  port: 8888

spring:
  application:
    name: EaiConfig
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/__dev__/code/EaiWorkspace/ConfigRepo