SERVICE_A=http://127.0.0.1:9001
SERVICE_B=http://127.0.0.1:9002
SERVICE_C=http://127.0.0.1:9003
SERVICE_D=http://127.0.0.1:9004
SERVICE_E=http://127.0.0.1:9005
SERVICE_F=http://127.0.0.1:9006
SERVICE_G=https://www.google.com
SERVICE_K=https://www.kbanknow.com
SERVICE_N=https://www.naver.com/
SERVICE_R=https://api.restful-api.dev/objects,,10,
SERVICE_L=https://www.swapi.tech/api/people/10,50000,40,30
SERVICE_Y=https://www.swapi.tech/api/people/20,50000,70,70